package com.qyp.dal.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ActivityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table activity
     *
     * @mbggenerated Wed Jun 01 10:29:29 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table activity
     *
     * @mbggenerated Wed Jun 01 10:29:29 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table activity
     *
     * @mbggenerated Wed Jun 01 10:29:29 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table activity
     *
     * @mbggenerated Wed Jun 01 10:29:29 CST 2016
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table activity
     *
     * @mbggenerated Wed Jun 01 10:29:29 CST 2016
     */
    protected int limitEnd = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated Wed Jun 01 10:29:29 CST 2016
     */
    public ActivityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated Wed Jun 01 10:29:29 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated Wed Jun 01 10:29:29 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated Wed Jun 01 10:29:29 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated Wed Jun 01 10:29:29 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated Wed Jun 01 10:29:29 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated Wed Jun 01 10:29:29 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated Wed Jun 01 10:29:29 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated Wed Jun 01 10:29:29 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated Wed Jun 01 10:29:29 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated Wed Jun 01 10:29:29 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated Wed Jun 01 10:29:29 CST 2016
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated Wed Jun 01 10:29:29 CST 2016
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated Wed Jun 01 10:29:29 CST 2016
     */
    public void setLimitEnd(int limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated Wed Jun 01 10:29:29 CST 2016
     */
    public int getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table activity
     *
     * @mbggenerated Wed Jun 01 10:29:29 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andActivityIdIsNull() {
            addCriterion("activity_id is null");
            return (Criteria) this;
        }

        public Criteria andActivityIdIsNotNull() {
            addCriterion("activity_id is not null");
            return (Criteria) this;
        }

        public Criteria andActivityIdEqualTo(Integer value) {
            addCriterion("activity_id =", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdNotEqualTo(Integer value) {
            addCriterion("activity_id <>", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdGreaterThan(Integer value) {
            addCriterion("activity_id >", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("activity_id >=", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdLessThan(Integer value) {
            addCriterion("activity_id <", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdLessThanOrEqualTo(Integer value) {
            addCriterion("activity_id <=", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdIn(List<Integer> values) {
            addCriterion("activity_id in", values, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdNotIn(List<Integer> values) {
            addCriterion("activity_id not in", values, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdBetween(Integer value1, Integer value2) {
            addCriterion("activity_id between", value1, value2, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdNotBetween(Integer value1, Integer value2) {
            addCriterion("activity_id not between", value1, value2, "activityId");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andActivityTitleIsNull() {
            addCriterion("activity_title is null");
            return (Criteria) this;
        }

        public Criteria andActivityTitleIsNotNull() {
            addCriterion("activity_title is not null");
            return (Criteria) this;
        }

        public Criteria andActivityTitleEqualTo(String value) {
            addCriterion("activity_title =", value, "activityTitle");
            return (Criteria) this;
        }

        public Criteria andActivityTitleNotEqualTo(String value) {
            addCriterion("activity_title <>", value, "activityTitle");
            return (Criteria) this;
        }

        public Criteria andActivityTitleGreaterThan(String value) {
            addCriterion("activity_title >", value, "activityTitle");
            return (Criteria) this;
        }

        public Criteria andActivityTitleGreaterThanOrEqualTo(String value) {
            addCriterion("activity_title >=", value, "activityTitle");
            return (Criteria) this;
        }

        public Criteria andActivityTitleLessThan(String value) {
            addCriterion("activity_title <", value, "activityTitle");
            return (Criteria) this;
        }

        public Criteria andActivityTitleLessThanOrEqualTo(String value) {
            addCriterion("activity_title <=", value, "activityTitle");
            return (Criteria) this;
        }

        public Criteria andActivityTitleLike(String value) {
            addCriterion("activity_title like", value, "activityTitle");
            return (Criteria) this;
        }

        public Criteria andActivityTitleNotLike(String value) {
            addCriterion("activity_title not like", value, "activityTitle");
            return (Criteria) this;
        }

        public Criteria andActivityTitleIn(List<String> values) {
            addCriterion("activity_title in", values, "activityTitle");
            return (Criteria) this;
        }

        public Criteria andActivityTitleNotIn(List<String> values) {
            addCriterion("activity_title not in", values, "activityTitle");
            return (Criteria) this;
        }

        public Criteria andActivityTitleBetween(String value1, String value2) {
            addCriterion("activity_title between", value1, value2, "activityTitle");
            return (Criteria) this;
        }

        public Criteria andActivityTitleNotBetween(String value1, String value2) {
            addCriterion("activity_title not between", value1, value2, "activityTitle");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("start_time is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("start_time is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(String value) {
            addCriterion("start_time =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(String value) {
            addCriterion("start_time <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(String value) {
            addCriterion("start_time >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(String value) {
            addCriterion("start_time >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(String value) {
            addCriterion("start_time <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(String value) {
            addCriterion("start_time <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLike(String value) {
            addCriterion("start_time like", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotLike(String value) {
            addCriterion("start_time not like", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<String> values) {
            addCriterion("start_time in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<String> values) {
            addCriterion("start_time not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(String value1, String value2) {
            addCriterion("start_time between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(String value1, String value2) {
            addCriterion("start_time not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(String value) {
            addCriterion("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(String value) {
            addCriterion("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(String value) {
            addCriterion("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(String value) {
            addCriterion("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(String value) {
            addCriterion("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(String value) {
            addCriterion("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLike(String value) {
            addCriterion("end_time like", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotLike(String value) {
            addCriterion("end_time not like", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<String> values) {
            addCriterion("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<String> values) {
            addCriterion("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(String value1, String value2) {
            addCriterion("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(String value1, String value2) {
            addCriterion("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andDestinationIsNull() {
            addCriterion("destination is null");
            return (Criteria) this;
        }

        public Criteria andDestinationIsNotNull() {
            addCriterion("destination is not null");
            return (Criteria) this;
        }

        public Criteria andDestinationEqualTo(String value) {
            addCriterion("destination =", value, "destination");
            return (Criteria) this;
        }

        public Criteria andDestinationNotEqualTo(String value) {
            addCriterion("destination <>", value, "destination");
            return (Criteria) this;
        }

        public Criteria andDestinationGreaterThan(String value) {
            addCriterion("destination >", value, "destination");
            return (Criteria) this;
        }

        public Criteria andDestinationGreaterThanOrEqualTo(String value) {
            addCriterion("destination >=", value, "destination");
            return (Criteria) this;
        }

        public Criteria andDestinationLessThan(String value) {
            addCriterion("destination <", value, "destination");
            return (Criteria) this;
        }

        public Criteria andDestinationLessThanOrEqualTo(String value) {
            addCriterion("destination <=", value, "destination");
            return (Criteria) this;
        }

        public Criteria andDestinationLike(String value) {
            addCriterion("destination like", value, "destination");
            return (Criteria) this;
        }

        public Criteria andDestinationNotLike(String value) {
            addCriterion("destination not like", value, "destination");
            return (Criteria) this;
        }

        public Criteria andDestinationIn(List<String> values) {
            addCriterion("destination in", values, "destination");
            return (Criteria) this;
        }

        public Criteria andDestinationNotIn(List<String> values) {
            addCriterion("destination not in", values, "destination");
            return (Criteria) this;
        }

        public Criteria andDestinationBetween(String value1, String value2) {
            addCriterion("destination between", value1, value2, "destination");
            return (Criteria) this;
        }

        public Criteria andDestinationNotBetween(String value1, String value2) {
            addCriterion("destination not between", value1, value2, "destination");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("creator like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("creator not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andMinPeopleSizeIsNull() {
            addCriterion("min_people_size is null");
            return (Criteria) this;
        }

        public Criteria andMinPeopleSizeIsNotNull() {
            addCriterion("min_people_size is not null");
            return (Criteria) this;
        }

        public Criteria andMinPeopleSizeEqualTo(Integer value) {
            addCriterion("min_people_size =", value, "minPeopleSize");
            return (Criteria) this;
        }

        public Criteria andMinPeopleSizeNotEqualTo(Integer value) {
            addCriterion("min_people_size <>", value, "minPeopleSize");
            return (Criteria) this;
        }

        public Criteria andMinPeopleSizeGreaterThan(Integer value) {
            addCriterion("min_people_size >", value, "minPeopleSize");
            return (Criteria) this;
        }

        public Criteria andMinPeopleSizeGreaterThanOrEqualTo(Integer value) {
            addCriterion("min_people_size >=", value, "minPeopleSize");
            return (Criteria) this;
        }

        public Criteria andMinPeopleSizeLessThan(Integer value) {
            addCriterion("min_people_size <", value, "minPeopleSize");
            return (Criteria) this;
        }

        public Criteria andMinPeopleSizeLessThanOrEqualTo(Integer value) {
            addCriterion("min_people_size <=", value, "minPeopleSize");
            return (Criteria) this;
        }

        public Criteria andMinPeopleSizeIn(List<Integer> values) {
            addCriterion("min_people_size in", values, "minPeopleSize");
            return (Criteria) this;
        }

        public Criteria andMinPeopleSizeNotIn(List<Integer> values) {
            addCriterion("min_people_size not in", values, "minPeopleSize");
            return (Criteria) this;
        }

        public Criteria andMinPeopleSizeBetween(Integer value1, Integer value2) {
            addCriterion("min_people_size between", value1, value2, "minPeopleSize");
            return (Criteria) this;
        }

        public Criteria andMinPeopleSizeNotBetween(Integer value1, Integer value2) {
            addCriterion("min_people_size not between", value1, value2, "minPeopleSize");
            return (Criteria) this;
        }

        public Criteria andMaxPeopleSizeIsNull() {
            addCriterion("max_people_size is null");
            return (Criteria) this;
        }

        public Criteria andMaxPeopleSizeIsNotNull() {
            addCriterion("max_people_size is not null");
            return (Criteria) this;
        }

        public Criteria andMaxPeopleSizeEqualTo(Integer value) {
            addCriterion("max_people_size =", value, "maxPeopleSize");
            return (Criteria) this;
        }

        public Criteria andMaxPeopleSizeNotEqualTo(Integer value) {
            addCriterion("max_people_size <>", value, "maxPeopleSize");
            return (Criteria) this;
        }

        public Criteria andMaxPeopleSizeGreaterThan(Integer value) {
            addCriterion("max_people_size >", value, "maxPeopleSize");
            return (Criteria) this;
        }

        public Criteria andMaxPeopleSizeGreaterThanOrEqualTo(Integer value) {
            addCriterion("max_people_size >=", value, "maxPeopleSize");
            return (Criteria) this;
        }

        public Criteria andMaxPeopleSizeLessThan(Integer value) {
            addCriterion("max_people_size <", value, "maxPeopleSize");
            return (Criteria) this;
        }

        public Criteria andMaxPeopleSizeLessThanOrEqualTo(Integer value) {
            addCriterion("max_people_size <=", value, "maxPeopleSize");
            return (Criteria) this;
        }

        public Criteria andMaxPeopleSizeIn(List<Integer> values) {
            addCriterion("max_people_size in", values, "maxPeopleSize");
            return (Criteria) this;
        }

        public Criteria andMaxPeopleSizeNotIn(List<Integer> values) {
            addCriterion("max_people_size not in", values, "maxPeopleSize");
            return (Criteria) this;
        }

        public Criteria andMaxPeopleSizeBetween(Integer value1, Integer value2) {
            addCriterion("max_people_size between", value1, value2, "maxPeopleSize");
            return (Criteria) this;
        }

        public Criteria andMaxPeopleSizeNotBetween(Integer value1, Integer value2) {
            addCriterion("max_people_size not between", value1, value2, "maxPeopleSize");
            return (Criteria) this;
        }

        public Criteria andBudgetIsNull() {
            addCriterion("budget is null");
            return (Criteria) this;
        }

        public Criteria andBudgetIsNotNull() {
            addCriterion("budget is not null");
            return (Criteria) this;
        }

        public Criteria andBudgetEqualTo(String value) {
            addCriterion("budget =", value, "budget");
            return (Criteria) this;
        }

        public Criteria andBudgetNotEqualTo(String value) {
            addCriterion("budget <>", value, "budget");
            return (Criteria) this;
        }

        public Criteria andBudgetGreaterThan(String value) {
            addCriterion("budget >", value, "budget");
            return (Criteria) this;
        }

        public Criteria andBudgetGreaterThanOrEqualTo(String value) {
            addCriterion("budget >=", value, "budget");
            return (Criteria) this;
        }

        public Criteria andBudgetLessThan(String value) {
            addCriterion("budget <", value, "budget");
            return (Criteria) this;
        }

        public Criteria andBudgetLessThanOrEqualTo(String value) {
            addCriterion("budget <=", value, "budget");
            return (Criteria) this;
        }

        public Criteria andBudgetLike(String value) {
            addCriterion("budget like", value, "budget");
            return (Criteria) this;
        }

        public Criteria andBudgetNotLike(String value) {
            addCriterion("budget not like", value, "budget");
            return (Criteria) this;
        }

        public Criteria andBudgetIn(List<String> values) {
            addCriterion("budget in", values, "budget");
            return (Criteria) this;
        }

        public Criteria andBudgetNotIn(List<String> values) {
            addCriterion("budget not in", values, "budget");
            return (Criteria) this;
        }

        public Criteria andBudgetBetween(String value1, String value2) {
            addCriterion("budget between", value1, value2, "budget");
            return (Criteria) this;
        }

        public Criteria andBudgetNotBetween(String value1, String value2) {
            addCriterion("budget not between", value1, value2, "budget");
            return (Criteria) this;
        }

        public Criteria andDepositIsNull() {
            addCriterion("deposit is null");
            return (Criteria) this;
        }

        public Criteria andDepositIsNotNull() {
            addCriterion("deposit is not null");
            return (Criteria) this;
        }

        public Criteria andDepositEqualTo(String value) {
            addCriterion("deposit =", value, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositNotEqualTo(String value) {
            addCriterion("deposit <>", value, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositGreaterThan(String value) {
            addCriterion("deposit >", value, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositGreaterThanOrEqualTo(String value) {
            addCriterion("deposit >=", value, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositLessThan(String value) {
            addCriterion("deposit <", value, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositLessThanOrEqualTo(String value) {
            addCriterion("deposit <=", value, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositLike(String value) {
            addCriterion("deposit like", value, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositNotLike(String value) {
            addCriterion("deposit not like", value, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositIn(List<String> values) {
            addCriterion("deposit in", values, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositNotIn(List<String> values) {
            addCriterion("deposit not in", values, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositBetween(String value1, String value2) {
            addCriterion("deposit between", value1, value2, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositNotBetween(String value1, String value2) {
            addCriterion("deposit not between", value1, value2, "deposit");
            return (Criteria) this;
        }

        public Criteria andDutyListIsNull() {
            addCriterion("duty_list is null");
            return (Criteria) this;
        }

        public Criteria andDutyListIsNotNull() {
            addCriterion("duty_list is not null");
            return (Criteria) this;
        }

        public Criteria andDutyListEqualTo(String value) {
            addCriterion("duty_list =", value, "dutyList");
            return (Criteria) this;
        }

        public Criteria andDutyListNotEqualTo(String value) {
            addCriterion("duty_list <>", value, "dutyList");
            return (Criteria) this;
        }

        public Criteria andDutyListGreaterThan(String value) {
            addCriterion("duty_list >", value, "dutyList");
            return (Criteria) this;
        }

        public Criteria andDutyListGreaterThanOrEqualTo(String value) {
            addCriterion("duty_list >=", value, "dutyList");
            return (Criteria) this;
        }

        public Criteria andDutyListLessThan(String value) {
            addCriterion("duty_list <", value, "dutyList");
            return (Criteria) this;
        }

        public Criteria andDutyListLessThanOrEqualTo(String value) {
            addCriterion("duty_list <=", value, "dutyList");
            return (Criteria) this;
        }

        public Criteria andDutyListLike(String value) {
            addCriterion("duty_list like", value, "dutyList");
            return (Criteria) this;
        }

        public Criteria andDutyListNotLike(String value) {
            addCriterion("duty_list not like", value, "dutyList");
            return (Criteria) this;
        }

        public Criteria andDutyListIn(List<String> values) {
            addCriterion("duty_list in", values, "dutyList");
            return (Criteria) this;
        }

        public Criteria andDutyListNotIn(List<String> values) {
            addCriterion("duty_list not in", values, "dutyList");
            return (Criteria) this;
        }

        public Criteria andDutyListBetween(String value1, String value2) {
            addCriterion("duty_list between", value1, value2, "dutyList");
            return (Criteria) this;
        }

        public Criteria andDutyListNotBetween(String value1, String value2) {
            addCriterion("duty_list not between", value1, value2, "dutyList");
            return (Criteria) this;
        }

        public Criteria andBoardListIsNull() {
            addCriterion("board_list is null");
            return (Criteria) this;
        }

        public Criteria andBoardListIsNotNull() {
            addCriterion("board_list is not null");
            return (Criteria) this;
        }

        public Criteria andBoardListEqualTo(String value) {
            addCriterion("board_list =", value, "boardList");
            return (Criteria) this;
        }

        public Criteria andBoardListNotEqualTo(String value) {
            addCriterion("board_list <>", value, "boardList");
            return (Criteria) this;
        }

        public Criteria andBoardListGreaterThan(String value) {
            addCriterion("board_list >", value, "boardList");
            return (Criteria) this;
        }

        public Criteria andBoardListGreaterThanOrEqualTo(String value) {
            addCriterion("board_list >=", value, "boardList");
            return (Criteria) this;
        }

        public Criteria andBoardListLessThan(String value) {
            addCriterion("board_list <", value, "boardList");
            return (Criteria) this;
        }

        public Criteria andBoardListLessThanOrEqualTo(String value) {
            addCriterion("board_list <=", value, "boardList");
            return (Criteria) this;
        }

        public Criteria andBoardListLike(String value) {
            addCriterion("board_list like", value, "boardList");
            return (Criteria) this;
        }

        public Criteria andBoardListNotLike(String value) {
            addCriterion("board_list not like", value, "boardList");
            return (Criteria) this;
        }

        public Criteria andBoardListIn(List<String> values) {
            addCriterion("board_list in", values, "boardList");
            return (Criteria) this;
        }

        public Criteria andBoardListNotIn(List<String> values) {
            addCriterion("board_list not in", values, "boardList");
            return (Criteria) this;
        }

        public Criteria andBoardListBetween(String value1, String value2) {
            addCriterion("board_list between", value1, value2, "boardList");
            return (Criteria) this;
        }

        public Criteria andBoardListNotBetween(String value1, String value2) {
            addCriterion("board_list not between", value1, value2, "boardList");
            return (Criteria) this;
        }

        public Criteria andPaymentUrlIsNull() {
            addCriterion("payment_url is null");
            return (Criteria) this;
        }

        public Criteria andPaymentUrlIsNotNull() {
            addCriterion("payment_url is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentUrlEqualTo(String value) {
            addCriterion("payment_url =", value, "paymentUrl");
            return (Criteria) this;
        }

        public Criteria andPaymentUrlNotEqualTo(String value) {
            addCriterion("payment_url <>", value, "paymentUrl");
            return (Criteria) this;
        }

        public Criteria andPaymentUrlGreaterThan(String value) {
            addCriterion("payment_url >", value, "paymentUrl");
            return (Criteria) this;
        }

        public Criteria andPaymentUrlGreaterThanOrEqualTo(String value) {
            addCriterion("payment_url >=", value, "paymentUrl");
            return (Criteria) this;
        }

        public Criteria andPaymentUrlLessThan(String value) {
            addCriterion("payment_url <", value, "paymentUrl");
            return (Criteria) this;
        }

        public Criteria andPaymentUrlLessThanOrEqualTo(String value) {
            addCriterion("payment_url <=", value, "paymentUrl");
            return (Criteria) this;
        }

        public Criteria andPaymentUrlLike(String value) {
            addCriterion("payment_url like", value, "paymentUrl");
            return (Criteria) this;
        }

        public Criteria andPaymentUrlNotLike(String value) {
            addCriterion("payment_url not like", value, "paymentUrl");
            return (Criteria) this;
        }

        public Criteria andPaymentUrlIn(List<String> values) {
            addCriterion("payment_url in", values, "paymentUrl");
            return (Criteria) this;
        }

        public Criteria andPaymentUrlNotIn(List<String> values) {
            addCriterion("payment_url not in", values, "paymentUrl");
            return (Criteria) this;
        }

        public Criteria andPaymentUrlBetween(String value1, String value2) {
            addCriterion("payment_url between", value1, value2, "paymentUrl");
            return (Criteria) this;
        }

        public Criteria andPaymentUrlNotBetween(String value1, String value2) {
            addCriterion("payment_url not between", value1, value2, "paymentUrl");
            return (Criteria) this;
        }

        public Criteria andActivityPhotoUrlIsNull() {
            addCriterion("activity_photo_url is null");
            return (Criteria) this;
        }

        public Criteria andActivityPhotoUrlIsNotNull() {
            addCriterion("activity_photo_url is not null");
            return (Criteria) this;
        }

        public Criteria andActivityPhotoUrlEqualTo(String value) {
            addCriterion("activity_photo_url =", value, "activityPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andActivityPhotoUrlNotEqualTo(String value) {
            addCriterion("activity_photo_url <>", value, "activityPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andActivityPhotoUrlGreaterThan(String value) {
            addCriterion("activity_photo_url >", value, "activityPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andActivityPhotoUrlGreaterThanOrEqualTo(String value) {
            addCriterion("activity_photo_url >=", value, "activityPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andActivityPhotoUrlLessThan(String value) {
            addCriterion("activity_photo_url <", value, "activityPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andActivityPhotoUrlLessThanOrEqualTo(String value) {
            addCriterion("activity_photo_url <=", value, "activityPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andActivityPhotoUrlLike(String value) {
            addCriterion("activity_photo_url like", value, "activityPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andActivityPhotoUrlNotLike(String value) {
            addCriterion("activity_photo_url not like", value, "activityPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andActivityPhotoUrlIn(List<String> values) {
            addCriterion("activity_photo_url in", values, "activityPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andActivityPhotoUrlNotIn(List<String> values) {
            addCriterion("activity_photo_url not in", values, "activityPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andActivityPhotoUrlBetween(String value1, String value2) {
            addCriterion("activity_photo_url between", value1, value2, "activityPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andActivityPhotoUrlNotBetween(String value1, String value2) {
            addCriterion("activity_photo_url not between", value1, value2, "activityPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andCreatorPhonenumberIsNull() {
            addCriterion("creator_phonenumber is null");
            return (Criteria) this;
        }

        public Criteria andCreatorPhonenumberIsNotNull() {
            addCriterion("creator_phonenumber is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorPhonenumberEqualTo(String value) {
            addCriterion("creator_phonenumber =", value, "creatorPhonenumber");
            return (Criteria) this;
        }

        public Criteria andCreatorPhonenumberNotEqualTo(String value) {
            addCriterion("creator_phonenumber <>", value, "creatorPhonenumber");
            return (Criteria) this;
        }

        public Criteria andCreatorPhonenumberGreaterThan(String value) {
            addCriterion("creator_phonenumber >", value, "creatorPhonenumber");
            return (Criteria) this;
        }

        public Criteria andCreatorPhonenumberGreaterThanOrEqualTo(String value) {
            addCriterion("creator_phonenumber >=", value, "creatorPhonenumber");
            return (Criteria) this;
        }

        public Criteria andCreatorPhonenumberLessThan(String value) {
            addCriterion("creator_phonenumber <", value, "creatorPhonenumber");
            return (Criteria) this;
        }

        public Criteria andCreatorPhonenumberLessThanOrEqualTo(String value) {
            addCriterion("creator_phonenumber <=", value, "creatorPhonenumber");
            return (Criteria) this;
        }

        public Criteria andCreatorPhonenumberLike(String value) {
            addCriterion("creator_phonenumber like", value, "creatorPhonenumber");
            return (Criteria) this;
        }

        public Criteria andCreatorPhonenumberNotLike(String value) {
            addCriterion("creator_phonenumber not like", value, "creatorPhonenumber");
            return (Criteria) this;
        }

        public Criteria andCreatorPhonenumberIn(List<String> values) {
            addCriterion("creator_phonenumber in", values, "creatorPhonenumber");
            return (Criteria) this;
        }

        public Criteria andCreatorPhonenumberNotIn(List<String> values) {
            addCriterion("creator_phonenumber not in", values, "creatorPhonenumber");
            return (Criteria) this;
        }

        public Criteria andCreatorPhonenumberBetween(String value1, String value2) {
            addCriterion("creator_phonenumber between", value1, value2, "creatorPhonenumber");
            return (Criteria) this;
        }

        public Criteria andCreatorPhonenumberNotBetween(String value1, String value2) {
            addCriterion("creator_phonenumber not between", value1, value2, "creatorPhonenumber");
            return (Criteria) this;
        }

        public Criteria andMoneyIsNull() {
            addCriterion("money is null");
            return (Criteria) this;
        }

        public Criteria andMoneyIsNotNull() {
            addCriterion("money is not null");
            return (Criteria) this;
        }

        public Criteria andMoneyEqualTo(String value) {
            addCriterion("money =", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotEqualTo(String value) {
            addCriterion("money <>", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyGreaterThan(String value) {
            addCriterion("money >", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyGreaterThanOrEqualTo(String value) {
            addCriterion("money >=", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyLessThan(String value) {
            addCriterion("money <", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyLessThanOrEqualTo(String value) {
            addCriterion("money <=", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyLike(String value) {
            addCriterion("money like", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotLike(String value) {
            addCriterion("money not like", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyIn(List<String> values) {
            addCriterion("money in", values, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotIn(List<String> values) {
            addCriterion("money not in", values, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyBetween(String value1, String value2) {
            addCriterion("money between", value1, value2, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotBetween(String value1, String value2) {
            addCriterion("money not between", value1, value2, "money");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table activity
     *
     * @mbggenerated do_not_delete_during_merge Wed Jun 01 10:29:29 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table activity
     *
     * @mbggenerated Wed Jun 01 10:29:29 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}