package com.qyp.dal.pojo;

import java.util.Date;

public class Activity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activity_id
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    private Integer activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.gmt_create
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.gmt_modified
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activity_title
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    private String activityTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.start_time
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.end_time
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    private String endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.destination
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    private String destination;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.creator
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.min_people_size
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    private Integer minPeopleSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.max_people_size
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    private Integer maxPeopleSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.budget
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    private String budget;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.deposit
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    private String deposit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.duty_list
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    private String dutyList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.board_list
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    private String boardList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.payment_url
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    private String paymentUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activity_photo_url
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    private String activityPhotoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.creator_phonenumber
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    private String creatorPhonenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.money
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    private String money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.status
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activity_id
     *
     * @return the value of activity.activity_id
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activity_id
     *
     * @param activityId the value for activity.activity_id
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.gmt_create
     *
     * @return the value of activity.gmt_create
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.gmt_create
     *
     * @param gmtCreate the value for activity.gmt_create
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.gmt_modified
     *
     * @return the value of activity.gmt_modified
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.gmt_modified
     *
     * @param gmtModified the value for activity.gmt_modified
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activity_title
     *
     * @return the value of activity.activity_title
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    public String getActivityTitle() {
        return activityTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activity_title
     *
     * @param activityTitle the value for activity.activity_title
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    public void setActivityTitle(String activityTitle) {
        this.activityTitle = activityTitle == null ? null : activityTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.start_time
     *
     * @return the value of activity.start_time
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.start_time
     *
     * @param startTime the value for activity.start_time
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.end_time
     *
     * @return the value of activity.end_time
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.end_time
     *
     * @param endTime the value for activity.end_time
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.destination
     *
     * @return the value of activity.destination
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    public String getDestination() {
        return destination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.destination
     *
     * @param destination the value for activity.destination
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    public void setDestination(String destination) {
        this.destination = destination == null ? null : destination.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.creator
     *
     * @return the value of activity.creator
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.creator
     *
     * @param creator the value for activity.creator
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.min_people_size
     *
     * @return the value of activity.min_people_size
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    public Integer getMinPeopleSize() {
        return minPeopleSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.min_people_size
     *
     * @param minPeopleSize the value for activity.min_people_size
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    public void setMinPeopleSize(Integer minPeopleSize) {
        this.minPeopleSize = minPeopleSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.max_people_size
     *
     * @return the value of activity.max_people_size
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    public Integer getMaxPeopleSize() {
        return maxPeopleSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.max_people_size
     *
     * @param maxPeopleSize the value for activity.max_people_size
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    public void setMaxPeopleSize(Integer maxPeopleSize) {
        this.maxPeopleSize = maxPeopleSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.budget
     *
     * @return the value of activity.budget
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    public String getBudget() {
        return budget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.budget
     *
     * @param budget the value for activity.budget
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    public void setBudget(String budget) {
        this.budget = budget == null ? null : budget.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.deposit
     *
     * @return the value of activity.deposit
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    public String getDeposit() {
        return deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.deposit
     *
     * @param deposit the value for activity.deposit
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    public void setDeposit(String deposit) {
        this.deposit = deposit == null ? null : deposit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.duty_list
     *
     * @return the value of activity.duty_list
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    public String getDutyList() {
        return dutyList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.duty_list
     *
     * @param dutyList the value for activity.duty_list
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    public void setDutyList(String dutyList) {
        this.dutyList = dutyList == null ? null : dutyList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.board_list
     *
     * @return the value of activity.board_list
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    public String getBoardList() {
        return boardList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.board_list
     *
     * @param boardList the value for activity.board_list
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    public void setBoardList(String boardList) {
        this.boardList = boardList == null ? null : boardList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.payment_url
     *
     * @return the value of activity.payment_url
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    public String getPaymentUrl() {
        return paymentUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.payment_url
     *
     * @param paymentUrl the value for activity.payment_url
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    public void setPaymentUrl(String paymentUrl) {
        this.paymentUrl = paymentUrl == null ? null : paymentUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activity_photo_url
     *
     * @return the value of activity.activity_photo_url
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    public String getActivityPhotoUrl() {
        return activityPhotoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activity_photo_url
     *
     * @param activityPhotoUrl the value for activity.activity_photo_url
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    public void setActivityPhotoUrl(String activityPhotoUrl) {
        this.activityPhotoUrl = activityPhotoUrl == null ? null : activityPhotoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.creator_phonenumber
     *
     * @return the value of activity.creator_phonenumber
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    public String getCreatorPhonenumber() {
        return creatorPhonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.creator_phonenumber
     *
     * @param creatorPhonenumber the value for activity.creator_phonenumber
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    public void setCreatorPhonenumber(String creatorPhonenumber) {
        this.creatorPhonenumber = creatorPhonenumber == null ? null : creatorPhonenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.money
     *
     * @return the value of activity.money
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    public String getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.money
     *
     * @param money the value for activity.money
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    public void setMoney(String money) {
        this.money = money == null ? null : money.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.status
     *
     * @return the value of activity.status
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.status
     *
     * @param status the value for activity.status
     *
     * @mbggenerated Tue May 31 09:58:44 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}