package com.qyp.dal.pojo;

public class ActivityWithBLOBs extends Activity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activity_description
     *
     * @mbggenerated Mon May 16 17:50:29 CST 2016
     */
    private String activityDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activity_content
     *
     * @mbggenerated Mon May 16 17:50:29 CST 2016
     */
    private String activityContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activity_description
     *
     * @return the value of activity.activity_description
     *
     * @mbggenerated Mon May 16 17:50:29 CST 2016
     */
    public String getActivityDescription() {
        return activityDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activity_description
     *
     * @param activityDescription the value for activity.activity_description
     *
     * @mbggenerated Mon May 16 17:50:29 CST 2016
     */
    public void setActivityDescription(String activityDescription) {
        this.activityDescription = activityDescription == null ? null : activityDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activity_content
     *
     * @return the value of activity.activity_content
     *
     * @mbggenerated Mon May 16 17:50:29 CST 2016
     */
    public String getActivityContent() {
        return activityContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activity_content
     *
     * @param activityContent the value for activity.activity_content
     *
     * @mbggenerated Mon May 16 17:50:29 CST 2016
     */
    public void setActivityContent(String activityContent) {
        this.activityContent = activityContent == null ? null : activityContent.trim();
    }
}