package com.qyp.dal.pojo;

import java.util.Date;

public class MemberActivity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_activity.id
     *
     * @mbggenerated Mon May 16 17:50:29 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_activity.gmt_create
     *
     * @mbggenerated Mon May 16 17:50:29 CST 2016
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_activity.gmt_modified
     *
     * @mbggenerated Mon May 16 17:50:29 CST 2016
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_activity.activity_id
     *
     * @mbggenerated Mon May 16 17:50:29 CST 2016
     */
    private Integer activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_activity.member_id
     *
     * @mbggenerated Mon May 16 17:50:29 CST 2016
     */
    private String memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_activity.duty
     *
     * @mbggenerated Mon May 16 17:50:29 CST 2016
     */
    private String duty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_activity.sing_up_status
     *
     * @mbggenerated Mon May 16 17:50:29 CST 2016
     */
    private String singUpStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_activity.is_deleted
     *
     * @mbggenerated Mon May 16 17:50:29 CST 2016
     */
    private String isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_activity.id
     *
     * @return the value of member_activity.id
     *
     * @mbggenerated Mon May 16 17:50:29 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_activity.id
     *
     * @param id the value for member_activity.id
     *
     * @mbggenerated Mon May 16 17:50:29 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_activity.gmt_create
     *
     * @return the value of member_activity.gmt_create
     *
     * @mbggenerated Mon May 16 17:50:29 CST 2016
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_activity.gmt_create
     *
     * @param gmtCreate the value for member_activity.gmt_create
     *
     * @mbggenerated Mon May 16 17:50:29 CST 2016
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_activity.gmt_modified
     *
     * @return the value of member_activity.gmt_modified
     *
     * @mbggenerated Mon May 16 17:50:29 CST 2016
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_activity.gmt_modified
     *
     * @param gmtModified the value for member_activity.gmt_modified
     *
     * @mbggenerated Mon May 16 17:50:29 CST 2016
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_activity.activity_id
     *
     * @return the value of member_activity.activity_id
     *
     * @mbggenerated Mon May 16 17:50:29 CST 2016
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_activity.activity_id
     *
     * @param activityId the value for member_activity.activity_id
     *
     * @mbggenerated Mon May 16 17:50:29 CST 2016
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_activity.member_id
     *
     * @return the value of member_activity.member_id
     *
     * @mbggenerated Mon May 16 17:50:29 CST 2016
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_activity.member_id
     *
     * @param memberId the value for member_activity.member_id
     *
     * @mbggenerated Mon May 16 17:50:29 CST 2016
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_activity.duty
     *
     * @return the value of member_activity.duty
     *
     * @mbggenerated Mon May 16 17:50:29 CST 2016
     */
    public String getDuty() {
        return duty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_activity.duty
     *
     * @param duty the value for member_activity.duty
     *
     * @mbggenerated Mon May 16 17:50:29 CST 2016
     */
    public void setDuty(String duty) {
        this.duty = duty == null ? null : duty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_activity.sing_up_status
     *
     * @return the value of member_activity.sing_up_status
     *
     * @mbggenerated Mon May 16 17:50:29 CST 2016
     */
    public String getSingUpStatus() {
        return singUpStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_activity.sing_up_status
     *
     * @param singUpStatus the value for member_activity.sing_up_status
     *
     * @mbggenerated Mon May 16 17:50:29 CST 2016
     */
    public void setSingUpStatus(String singUpStatus) {
        this.singUpStatus = singUpStatus == null ? null : singUpStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_activity.is_deleted
     *
     * @return the value of member_activity.is_deleted
     *
     * @mbggenerated Mon May 16 17:50:29 CST 2016
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_activity.is_deleted
     *
     * @param isDeleted the value for member_activity.is_deleted
     *
     * @mbggenerated Mon May 16 17:50:29 CST 2016
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }
}