package com.qyp.dal.pojo;

import java.util.Date;

public class Member {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.id
     *
     * @mbggenerated Wed Jun 01 10:41:45 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.gmt_create
     *
     * @mbggenerated Wed Jun 01 10:41:45 CST 2016
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.gmt_modified
     *
     * @mbggenerated Wed Jun 01 10:41:45 CST 2016
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.member_id
     *
     * @mbggenerated Wed Jun 01 10:41:45 CST 2016
     */
    private String memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.nick_name
     *
     * @mbggenerated Wed Jun 01 10:41:45 CST 2016
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.age
     *
     * @mbggenerated Wed Jun 01 10:41:45 CST 2016
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.sex
     *
     * @mbggenerated Wed Jun 01 10:41:45 CST 2016
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.talent
     *
     * @mbggenerated Wed Jun 01 10:41:45 CST 2016
     */
    private String talent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.is_single
     *
     * @mbggenerated Wed Jun 01 10:41:45 CST 2016
     */
    private String isSingle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.phone_number
     *
     * @mbggenerated Wed Jun 01 10:41:45 CST 2016
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.email
     *
     * @mbggenerated Wed Jun 01 10:41:45 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.is_deleted
     *
     * @mbggenerated Wed Jun 01 10:41:45 CST 2016
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.pass_port
     *
     * @mbggenerated Wed Jun 01 10:41:45 CST 2016
     */
    private String passPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.real_name
     *
     * @mbggenerated Wed Jun 01 10:41:45 CST 2016
     */
    private String realName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.id
     *
     * @return the value of member.id
     *
     * @mbggenerated Wed Jun 01 10:41:45 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.id
     *
     * @param id the value for member.id
     *
     * @mbggenerated Wed Jun 01 10:41:45 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.gmt_create
     *
     * @return the value of member.gmt_create
     *
     * @mbggenerated Wed Jun 01 10:41:45 CST 2016
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.gmt_create
     *
     * @param gmtCreate the value for member.gmt_create
     *
     * @mbggenerated Wed Jun 01 10:41:45 CST 2016
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.gmt_modified
     *
     * @return the value of member.gmt_modified
     *
     * @mbggenerated Wed Jun 01 10:41:45 CST 2016
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.gmt_modified
     *
     * @param gmtModified the value for member.gmt_modified
     *
     * @mbggenerated Wed Jun 01 10:41:45 CST 2016
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.member_id
     *
     * @return the value of member.member_id
     *
     * @mbggenerated Wed Jun 01 10:41:45 CST 2016
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.member_id
     *
     * @param memberId the value for member.member_id
     *
     * @mbggenerated Wed Jun 01 10:41:45 CST 2016
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.nick_name
     *
     * @return the value of member.nick_name
     *
     * @mbggenerated Wed Jun 01 10:41:45 CST 2016
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.nick_name
     *
     * @param nickName the value for member.nick_name
     *
     * @mbggenerated Wed Jun 01 10:41:45 CST 2016
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.age
     *
     * @return the value of member.age
     *
     * @mbggenerated Wed Jun 01 10:41:45 CST 2016
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.age
     *
     * @param age the value for member.age
     *
     * @mbggenerated Wed Jun 01 10:41:45 CST 2016
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.sex
     *
     * @return the value of member.sex
     *
     * @mbggenerated Wed Jun 01 10:41:45 CST 2016
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.sex
     *
     * @param sex the value for member.sex
     *
     * @mbggenerated Wed Jun 01 10:41:45 CST 2016
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.talent
     *
     * @return the value of member.talent
     *
     * @mbggenerated Wed Jun 01 10:41:45 CST 2016
     */
    public String getTalent() {
        return talent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.talent
     *
     * @param talent the value for member.talent
     *
     * @mbggenerated Wed Jun 01 10:41:45 CST 2016
     */
    public void setTalent(String talent) {
        this.talent = talent == null ? null : talent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.is_single
     *
     * @return the value of member.is_single
     *
     * @mbggenerated Wed Jun 01 10:41:45 CST 2016
     */
    public String getIsSingle() {
        return isSingle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.is_single
     *
     * @param isSingle the value for member.is_single
     *
     * @mbggenerated Wed Jun 01 10:41:45 CST 2016
     */
    public void setIsSingle(String isSingle) {
        this.isSingle = isSingle == null ? null : isSingle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.phone_number
     *
     * @return the value of member.phone_number
     *
     * @mbggenerated Wed Jun 01 10:41:45 CST 2016
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.phone_number
     *
     * @param phoneNumber the value for member.phone_number
     *
     * @mbggenerated Wed Jun 01 10:41:45 CST 2016
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.email
     *
     * @return the value of member.email
     *
     * @mbggenerated Wed Jun 01 10:41:45 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.email
     *
     * @param email the value for member.email
     *
     * @mbggenerated Wed Jun 01 10:41:45 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.is_deleted
     *
     * @return the value of member.is_deleted
     *
     * @mbggenerated Wed Jun 01 10:41:45 CST 2016
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.is_deleted
     *
     * @param isDeleted the value for member.is_deleted
     *
     * @mbggenerated Wed Jun 01 10:41:45 CST 2016
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.pass_port
     *
     * @return the value of member.pass_port
     *
     * @mbggenerated Wed Jun 01 10:41:45 CST 2016
     */
    public String getPassPort() {
        return passPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.pass_port
     *
     * @param passPort the value for member.pass_port
     *
     * @mbggenerated Wed Jun 01 10:41:45 CST 2016
     */
    public void setPassPort(String passPort) {
        this.passPort = passPort == null ? null : passPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.real_name
     *
     * @return the value of member.real_name
     *
     * @mbggenerated Wed Jun 01 10:41:45 CST 2016
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.real_name
     *
     * @param realName the value for member.real_name
     *
     * @mbggenerated Wed Jun 01 10:41:45 CST 2016
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }
}