package com.qyp.dal.mapper;

import com.qyp.dal.pojo.MemberActivity;
import com.qyp.dal.pojo.MemberActivityExample;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MemberActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_activity
     *
     * @mbggenerated Wed Jun 01 10:29:29 CST 2016
     */
    int countByExample(MemberActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_activity
     *
     * @mbggenerated Wed Jun 01 10:29:29 CST 2016
     */
    int deleteByExample(MemberActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_activity
     *
     * @mbggenerated Wed Jun 01 10:29:29 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_activity
     *
     * @mbggenerated Wed Jun 01 10:29:29 CST 2016
     */
    int insert(MemberActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_activity
     *
     * @mbggenerated Wed Jun 01 10:29:29 CST 2016
     */
    int insertSelective(MemberActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_activity
     *
     * @mbggenerated Wed Jun 01 10:29:29 CST 2016
     */
    List<MemberActivity> selectByExample(MemberActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_activity
     *
     * @mbggenerated Wed Jun 01 10:29:29 CST 2016
     */
    MemberActivity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_activity
     *
     * @mbggenerated Wed Jun 01 10:29:29 CST 2016
     */
    int updateByExampleSelective(@Param("record") MemberActivity record, @Param("example") MemberActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_activity
     *
     * @mbggenerated Wed Jun 01 10:29:29 CST 2016
     */
    int updateByExample(@Param("record") MemberActivity record, @Param("example") MemberActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_activity
     *
     * @mbggenerated Wed Jun 01 10:29:29 CST 2016
     */
    int updateByPrimaryKeySelective(MemberActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_activity
     *
     * @mbggenerated Wed Jun 01 10:29:29 CST 2016
     */
    int updateByPrimaryKey(MemberActivity record);
}